behaviors:
  MLAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64  # Reduced batch size for limited resources
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128  # Reduced the number of hidden units
      num_layers: 3
      vis_encode_type: simple
      memory:
        use_recurrent: false  # LSTM enabled
        sequence_length: 64  # Reduced sequence length
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 2
    max_steps: 10000000
    time_horizon: 64  # Reduced time horizon
    summary_freq: 10000
    threaded: false


environment_parameters:
  pallet_percentage:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: MLAgent
          signal_smoothing: true
          min_lesson_length: 100000
          threshold: 0.2
        value: 0.1
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: MLAgent
          signal_smoothing: true
          min_lesson_length: 100000
          threshold: 0.4
        value: 0.2
      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: MLAgent
          signal_smoothing: true
          min_lesson_length: 100000
          threshold: 0.6
        value: 0.4
      - name: Lesson4
        completion_criteria:
          measure: progress
          behavior: MLAgent
          signal_smoothing: true
          min_lesson_length: 100000
          threshold: 0.8
        value: 0.6
      - name: Lesson5
        completion_criteria:
          measure: progress
          behavior: MLAgent
          signal_smoothing: true
          min_lesson_length: 100000
          threshold: 1.0
        value: 0.8
      - name: Lesson6
        value: 1.0

